# Generated by Django 6.1.1 on 2026-10-03 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_cancelled_at'),
        ('shop', '0003_alter_category_name_alter_location_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='expires_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.location'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_code',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
    ]
