# Generated by Django 6.1.1 on 2026-10-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
